### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by hhegab** [parthpanchal123/Share-Space#2]
Error complains file "donate.dart" does not exist.

**Comment by parthpanchal123** [comment]
> Error complains file "donate.dart" does not exist.

The file Donate.dart contains credentials like ad ids and stuff so i put it in . gitignore . On which page/file is the error thrown from ? Because currently it doesn't contain references to donate.dart.

**Comment by parthpanchal123** [comment]
Closing this issue for now.
